import os
import pyautogui
import time
os.system("/opt/google/chrome/google-chrome --profile-directory=Default --app-id=menkifleemblimdogmoihpfopnplikde")
time.sleep(5)
pyautogui.click(x=287, y=223, clicks=1, interval=0, button='left')
# pyautogui.typewrite('mrangga.perm@gmail.com')
pyautogui.press('tab')
pyautogui.typewrite('golkar05')
pyautogui.click(x=348, y=336, clicks=1, interval=0, button='left')
time.sleep(10)
# # (348, 336)
# pyautogui.hotkey('alt','tab')
# pyautogui.click(x=361, y=287, clicks=1, interval=0, button='left')
# pyautogui.click(x=174, y=283, clicks=1, interval=0, button='left')
# time.sleep(3)
# pyautogui.typewrite('85771467766')
# time.sleep(3)
# pyautogui.press('enter')
# pyautogui.click(x=234, y=447, clicks=1, interval=0, button='left')
# time.sleep(2)
# pyautogui.click(x=234, y=447, clicks=1, interval=0, button='left')
# time.sleep(2)
# pyautogui.click(x=234, y=447, clicks=1, interval=0, button='left')